# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 26 Nov 2012 20:20:03 +0000
*               @ALL          1
*               @user         8
