<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: administrator
 * Date: Tue, 25 Dec 2012 08:56:40 +1100
 */

$conf['title'] = 'Standards Library';
$conf['template'] = 'SparklingSoftware';
$conf['tagline'] = 'The WikiPedia of IT Processes';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['sitemap'] = 1;
$conf['renderer_xhtml'] = 'xbr';
$conf['plugin']['quickstats']['geoip_local'] = 1;
$conf['plugin']['quickstats']['geoplugin'] = 0;

// end auto-generated content
