<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: administrator
 * Date: Tue, 27 Nov 2012 08:02:34 +1100
 */

$conf['title'] = 'Standards Library';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['renderer_xhtml'] = 'xbr';

// end auto-generated content
