<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: administrator
 * Date: Thu, 17 Jan 2013 09:45:35 +1100
 */

$conf['title'] = 'Standards Library';
$conf['template'] = 'SparklingSoftware';
$conf['tagline'] = 'The WikiPedia of IT Processes';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['sitemap'] = 1;
$conf['renderer_xhtml'] = 'xbr';
$conf['plugin']['branches']['branch_prefix'] = 'ALM-';
$conf['plugin']['quickstats']['geoip_local'] = 1;
$conf['plugin']['quickstats']['geoplugin'] = 0;
$conf['tpl']['SparklingSoftware']['monobook_donate'] = 0;
$conf['tpl']['SparklingSoftware']['monobook_donate_default'] = 0;

// end auto-generated content
